import { describe, expect, it } from "vitest";
import { computeCropBounds } from "@/lib/ai/orchestration/imageAutoCrop";

describe("Image Auto-Crop & Letterbox Trimming", () => {
  it("computes accurate crop bounds for wide panoramic banner (e.g. 60x20cm = 3:1) from 16:9 base image", () => {
    // 16:9 base image generated by AI provider (1536x864, ratio ~1.778)
    const sourceWidth = 1536;
    const sourceHeight = 864;
    const targetRatio = 3.0; // 3:1 (60x20cm)

    const bounds = computeCropBounds(sourceWidth, sourceHeight, targetRatio);

    expect(bounds.cropWidth).toBe(1536);
    expect(bounds.cropHeight).toBe(512); // 1536 / 3.0 = 512
    expect(bounds.cropX).toBe(0);
    expect(bounds.cropY).toBe(176); // (864 - 512) / 2 = 176 (center crop)
  });

  it("centers content accurately between detected letterbox bars", () => {
    const sourceWidth = 1536;
    const sourceHeight = 864;
    const targetRatio = 3.0; // 512px height
    const letterboxTop = 180;
    const letterboxBottom = 172;

    const bounds = computeCropBounds(
      sourceWidth,
      sourceHeight,
      targetRatio,
      letterboxTop,
      letterboxBottom,
    );

    expect(bounds.cropWidth).toBe(1536);
    expect(bounds.cropHeight).toBe(512);
    // Active content center: (180 + (864 - 172)) / 2 = (180 + 692) / 2 = 436
    // cropY: 436 - 256 = 180
    expect(bounds.cropY).toBe(180);
  });

  it("computes accurate crop bounds for vertical skyscraper banner (e.g. 1:3) from 9:16 base image", () => {
    const sourceWidth = 720;
    const sourceHeight = 1280;
    const targetRatio = 1 / 3; // 1:3 vertical

    const bounds = computeCropBounds(sourceWidth, sourceHeight, targetRatio);

    expect(bounds.cropHeight).toBe(1280);
    expect(bounds.cropWidth).toBe(427); // 1280 * (1/3) = ~427
    expect(bounds.cropY).toBe(0);
    expect(bounds.cropX).toBe(Math.floor((720 - 427) / 2));
  });

  it("bypasses cropping when image already matches target ratio within tolerance", () => {
    const sourceWidth = 1024;
    const sourceHeight = 1024;
    const targetRatio = 1.0;

    const bounds = computeCropBounds(sourceWidth, sourceHeight, targetRatio);

    expect(bounds.cropWidth).toBe(1024);
    expect(bounds.cropHeight).toBe(1024);
    expect(bounds.cropX).toBe(0);
    expect(bounds.cropY).toBe(0);
  });
});
