import type { TextEffectSourceSpec } from "./types";

export const TEXT_EFFECT_SOURCE_SPECS: TextEffectSourceSpec[] = [
  {
    id: 1,
    name: "Borealis",
    slug: "aurora",
    description: "aurora gradient drifting through the letters",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "skew_rotate",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 2,
    name: "Glitchcore",
    slug: "glitch",
    description: "RGB channel-split glitch with sliced jumps",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: -4, offsetY: -1, opacity: 0.85 },
      { color: "var(--ink-3)", offsetX: 4, offsetY: 1, opacity: 0.85 },
    ],
  },
  {
    id: 3,
    name: "Teletype",
    slug: "typewriter",
    description: "typewriter with blinking caret (word must match the ch width)",
    family: "frozen_motion",
    staticCaps: ["transparent_fill", "letter_spacing", "ink_tokens"],
    letterSpacingEm: 0,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 4,
    name: "Neon-Haus",
    slug: "neon",
    description: "buzzing neon sign with unstable tube flicker",
    family: "neon_glow",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 4, color: "var(--ink)" },
      { offsetX: 0, offsetY: 0, blur: 11, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 0, blur: 24, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 0, blur: 48, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 0, blur: 4, color: "var(--ink-2)" },
    ],
  },
  {
    id: 5,
    name: "Aqua-Fill",
    slug: "liquid",
    description: "the word fills with liquid that rises and drains",
    family: "liquid_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "text_stroke",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    stroke: { width: 1, color: "color-mix(in srgb, var(--ink-3) 65%, transparent)" },
    shadows: [],
  },
  {
    id: 6,
    name: "Chromia",
    slug: "chrome",
    description: "brushed-metal letters with a passing sheen",
    family: "chrome_metal",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 7,
    name: "Lens-Drift",
    slug: "focus",
    description: "letters slip in and out of focus, one after another",
    family: "soft_blur_bloom",
    staticCaps: ["letter_spacing", "ink_tokens", "opacity_layers", "filter_blur"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    blurRadius: 3,
  },
  {
    id: 8,
    name: "Tidal-Type",
    slug: "wave",
    description: "letters ride a rolling sine wave",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-3)",
    shadows: [],
  },
  {
    id: 9,
    name: "Bisect",
    slug: "sliced",
    description: "the word is sliced horizontally; halves drift apart and re-align",
    family: "cutout_layers",
    staticCaps: [
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: 8, offsetY: -6, opacity: 0.9 },
      { color: "var(--ink-3)", offsetX: -8, offsetY: 6, opacity: 0.9 },
    ],
  },
  {
    id: 10,
    name: "Cipher",
    slug: "decoder",
    description: "scrambled characters decode into the word, then re-encrypt",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "pseudo_layers"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-3)",
    shadows: [],
  },
  {
    id: 11,
    name: "Redactor",
    slug: "scanner",
    description: "a scanning bar sweeps the word, lighting letters as it passes",
    family: "cutout_layers",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 12,
    name: "Emberglow",
    slug: "ember",
    description: "letters smoulder under rising fire light",
    family: "neon_glow",
    staticCaps: ["letter_spacing", "text_shadow_stack", "multi_text_shadow"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "#ffd9a0",
    shadows: [
      { offsetX: 0, offsetY: -2, blur: 6, color: "#ffab40" },
      { offsetX: 0, offsetY: -6, blur: 14, color: "#ff6d00" },
      { offsetX: 0, offsetY: -12, blur: 28, color: "#dd2c00" },
      { offsetX: 0, offsetY: -20, blur: 44, color: "rgba(213,0,0,.55)" },
      { offsetX: 0, offsetY: -3, blur: 8, color: "#ffc46b" },
      { offsetX: 0, offsetY: -9, blur: 20, color: "#ff8f1f" },
      { offsetX: 0, offsetY: -18, blur: 38, color: "#ff3d00" },
      { offsetX: 0, offsetY: -30, blur: 60, color: "rgba(213,0,0,.8)" },
    ],
  },
  {
    id: 13,
    name: "Echo-Verse",
    slug: "echo",
    description: "ghost copies of the word ripple outward",
    family: "outline_stroke",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "filter_blur",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    blurRadius: 2,
  },
  {
    id: 14,
    name: "Deep-Type",
    slug: "extrude",
    description: "extruded 3D block letters rocking on their axis",
    family: "emboss_3d",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 1, offsetY: 1, blur: 0, color: "color-mix(in srgb,var(--ink-2) 80%,#000)" },
      { offsetX: 2, offsetY: 2, blur: 0, color: "color-mix(in srgb,var(--ink-2) 70%,#000)" },
      { offsetX: 3, offsetY: 3, blur: 0, color: "color-mix(in srgb,var(--ink-2) 60%,#000)" },
      { offsetX: 4, offsetY: 4, blur: 0, color: "color-mix(in srgb,var(--ink-2) 50%,#000)" },
      { offsetX: 5, offsetY: 5, blur: 0, color: "color-mix(in srgb,var(--ink-2) 40%,#000)" },
      { offsetX: 6, offsetY: 6, blur: 0, color: "color-mix(in srgb,var(--ink-2) 30%,#000)" },
      { offsetX: 7, offsetY: 7, blur: 12, color: "rgba(0,0,0,.5)" },
    ],
  },
  {
    id: 15,
    name: "Wireframe",
    slug: "contour",
    description: "a dashed outline endlessly traces the letterforms",
    family: "outline_stroke",
    staticCaps: ["letter_spacing", "ink_tokens"],
    letterSpacingEm: 0.02,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 16,
    name: "Prisma",
    slug: "spectrum",
    description: "each letter refracts a different band of the spectrum",
    family: "gradient_aurora",
    staticCaps: ["letter_spacing", "skew_rotate"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "#ff2d78",
    shadows: [],
  },
  {
    id: 17,
    name: "Jitterbug",
    slug: "jitter",
    description: "nervous analogue jitter: skews, jumps and dropped frames",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "opacity_layers", "skew_rotate"],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 18,
    name: "Anaglyph-3D",
    slug: "anaglyph",
    description: "red/cyan stereo channels drift apart and snap back",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "multi_text_shadow",
      "data_text_dupe",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 0, color: "#ff3355" },
      { offsetX: 0, offsetY: 0, blur: 0, color: "#33ddff" },
      { offsetX: -6, offsetY: 0, blur: 1, color: "#ff3355" },
      { offsetX: 6, offsetY: 0, blur: 1, color: "#33ddff" },
    ],
    offsetFills: [
      { color: "#ff3355", offsetX: -5, offsetY: 0, opacity: 0.9 },
      { color: "#33ddff", offsetX: 5, offsetY: 0, opacity: 0.9 },
    ],
  },
  {
    id: 19,
    name: "Split-Flap",
    slug: "flap",
    description: "airport departure board; letters flip on their plates",
    family: "frozen_motion",
    staticCaps: ["gradient_fill", "letter_spacing", "ink_tokens"],
    letterSpacingEm: 0,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 20,
    name: "Phosphor",
    slug: "crt",
    description: "CRT terminal: green glow, rolling scanlines, tube flicker",
    family: "neon_glow",
    staticCaps: [
      "gradient_fill",
      "letter_spacing",
      "pseudo_layers",
      "opacity_layers",
      "text_shadow_stack",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "#4dff88",
    shadows: [{ offsetX: 0, offsetY: 0, blur: 7, color: "rgba(77,255,136,.8)" }],
  },
  {
    id: 21,
    name: "Pop-Riot",
    slug: "pop",
    description: "letters leap with a hard comic-book drop shadow",
    family: "emboss_3d",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.04,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 12, blur: 0, color: "var(--ink-2)" },
    ],
  },
  {
    id: 22,
    name: "Limelight",
    slug: "spotlight",
    description: "a spotlight sweeps across otherwise unlit letters",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 23,
    name: "Rubber-Band",
    slug: "elastic",
    description: "the word squashes and stretches like an elastic band",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-2)",
    shadows: [],
  },
  {
    id: 24,
    name: "Still-Water",
    slug: "mirror",
    description:
      "the word floats over its own rippling reflection (uses -webkit-box-reflect: Chromium & Safari; degrades gracefully)",
    family: "liquid_fill",
    staticCaps: ["gradient_fill", "letter_spacing", "ink_tokens", "box_reflect"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: true,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 25,
    name: "Ransom-Note",
    slug: "ransom",
    description: "mismatched cut-out letters shifting on the page",
    family: "cutout_layers",
    staticCaps: ["letter_spacing", "ink_tokens", "skew_rotate"],
    letterSpacingEm: 0,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 26,
    name: "Meltdown",
    slug: "melt",
    description: "letters sag, stretch and drip before snapping back",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "filter_blur"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-2)",
    shadows: [],
  },
  {
    id: 27,
    name: "Cardio",
    slug: "heartbeat",
    description: "a lub-dub heartbeat with a systolic glow",
    family: "neon_glow",
    staticCaps: ["letter_spacing", "ink_tokens", "text_shadow_stack", "multi_text_shadow"],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-2)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 0, color: "transparent" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 18,
        color: "color-mix(in srgb,var(--ink-2) 65%,transparent)",
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 26,
        color: "color-mix(in srgb,var(--ink-2) 80%,transparent)",
      },
      { offsetX: 0, offsetY: 0, blur: 0, color: "transparent" },
    ],
  },
  {
    id: 28,
    name: "Hi-Liter",
    slug: "marker",
    description: "a marker pen paints across the word, then lifts off",
    family: "gradient_aurora",
    staticCaps: ["gradient_fill", "letter_spacing", "ink_tokens"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 29,
    name: "Sundial",
    slug: "sundial",
    description: "a long cast shadow circles the letters like a passing sun",
    family: "emboss_3d",
    staticCaps: ["letter_spacing", "ink_tokens", "text_shadow_stack", "multi_text_shadow"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 4, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: 8, offsetY: 0, blur: 0, color: "color-mix(in srgb,var(--ink-2) 55%,transparent)" },
      {
        offsetX: 12,
        offsetY: 0,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: 2.8, offsetY: 2.8, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: 5.6,
        offsetY: 5.6,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: 8.4,
        offsetY: 8.4,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: 0, offsetY: 4, blur: 0, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 8, blur: 0, color: "color-mix(in srgb,var(--ink-2) 55%,transparent)" },
      {
        offsetX: 0,
        offsetY: 12,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: -2.8, offsetY: 2.8, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: -5.6,
        offsetY: 5.6,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: -8.4,
        offsetY: 8.4,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: -4, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: -8,
        offsetY: 0,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: -12,
        offsetY: 0,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: -2.8, offsetY: -2.8, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: -5.6,
        offsetY: -5.6,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: -8.4,
        offsetY: -8.4,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: 0, offsetY: -4, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: 0,
        offsetY: -8,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: 0,
        offsetY: -12,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
      { offsetX: 2.8, offsetY: -2.8, blur: 0, color: "var(--ink-2)" },
      {
        offsetX: 5.6,
        offsetY: -5.6,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 55%,transparent)",
      },
      {
        offsetX: 8.4,
        offsetY: -8.4,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 25%,transparent)",
      },
    ],
  },
  {
    id: 30,
    name: "Negativ",
    slug: "negative",
    description:
      "an inversion bar sweeps the word, flipping letters to their photographic negative via mix-blend-mode: difference",
    family: "cutout_layers",
    staticCaps: ["letter_spacing", "ink_tokens", "pseudo_layers", "mix_blend"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    blend: "difference",
    shadows: [],
  },
  {
    id: 31,
    name: "Holograph",
    slug: "hologram",
    description: "translucent scanline projection with drifting chroma edges",
    family: "holographic",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink-3) 72%, var(--ink))",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 6, color: "color-mix(in srgb,var(--ink-3) 60%,transparent)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 22,
        color: "color-mix(in srgb,var(--ink-3) 45%,transparent)",
      },
    ],
  },
  {
    id: 32,
    name: "Gold-Foil",
    slug: "foil",
    description: "embossed metallic letters with a diagonal specular sweep",
    family: "chrome_metal",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 1, blur: 0, color: "rgba(255,244,184,.45)" },
      { offsetX: 0, offsetY: 9, blur: 20, color: "rgba(0,0,0,.36)" },
    ],
  },
  {
    id: 33,
    name: "Pixel-Sort",
    slug: "pixel",
    description: "blocky offsets smear the word into stepped digital columns",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 1, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: -1, offsetY: 0, blur: 0, color: "var(--ink-3)" },
    ],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: 5, offsetY: -2, opacity: 0.8 },
      { color: "var(--ink-3)", offsetX: -5, offsetY: 2, opacity: 0.8 },
    ],
  },
  {
    id: 34,
    name: "Starlight",
    slug: "starlight",
    description: "a constellation shimmer twinkles across frosted letter faces",
    family: "neon_glow",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 35,
    name: "Blueprint",
    slug: "blueprint",
    description: "technical outline letters over a moving drafting grid",
    family: "outline_stroke",
    staticCaps: [
      "gradient_fill",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "text_stroke",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    stroke: { width: 1, color: "color-mix(in srgb, var(--ink-3) 80%, var(--ink))" },
    shadows: [],
  },
  {
    id: 36,
    name: "Vapor-Trail",
    slug: "vapor",
    description: "soft neon copies trail behind a drifting word",
    family: "neon_glow",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
      "filter_blur",
    ],
    letterSpacingEm: 0.16,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 12, color: "color-mix(in srgb,var(--ink) 45%,transparent)" },
    ],
  },
  {
    id: 37,
    name: "Kinetic-Type",
    slug: "kinetic",
    description: "characters slide on staggered rails and lock into place",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "filter_blur", "skew_rotate"],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 38,
    name: "Blackout",
    slug: "blackout",
    description: "redaction strips repeatedly hide and reveal classified text",
    family: "cutout_layers",
    staticCaps: ["letter_spacing", "ink_tokens", "pseudo_layers"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 39,
    name: "Magnetic",
    slug: "magnetic",
    description: "letters attract into a tight field, then repel outward",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "text_shadow_stack", "multi_text_shadow"],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 0, blur: 0, color: "transparent" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 16,
        color: "color-mix(in srgb,var(--ink-2) 70%,transparent)",
      },
    ],
  },
  {
    id: 40,
    name: "Luma-Mesh",
    slug: "mesh",
    description: "animated mesh-gradient ink with a soft luminous edge",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 41,
    name: "Iridescent",
    slug: "iridescent",
    description: "pearlescent text whose colour shifts with a moving angle",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "skew_rotate",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [{ offsetX: 0, offsetY: 10, blur: 28, color: "rgba(0,0,0,.28)" }],
  },
  {
    id: 42,
    name: "Glass-Type",
    slug: "glass",
    description: "translucent frosted letters with an offset refraction layer",
    family: "soft_blur_bloom",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
      "text_stroke",
      "filter_blur",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink) 58%, transparent)",
    stroke: { width: 1, color: "color-mix(in srgb, var(--ink) 52%, transparent)" },
    shadows: [
      { offsetX: 0, offsetY: 1, blur: 0, color: "rgba(255,255,255,.4)" },
      { offsetX: 0, offsetY: 12, blur: 24, color: "rgba(0,0,0,.3)" },
    ],
    blurRadius: 2.5,
  },
  {
    id: 43,
    name: "Datastream",
    slug: "datastream",
    description: "matrix-like data bands flow through clipped letterforms",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "opacity_layers",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 44,
    name: "Orbitals",
    slug: "orbit",
    description: "letters circle tiny invisible tracks before settling back",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "skew_rotate"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 45,
    name: "Prism-Cut",
    slug: "prismcut",
    description: "diagonal glass shards refract the word into colour offsets",
    family: "cutout_layers",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: -6, offsetY: -3, opacity: 0.8 },
      { color: "var(--ink-3)", offsetX: 6, offsetY: 3, opacity: 0.8 },
    ],
  },
  {
    id: 46,
    name: "Soft-Blur",
    slug: "softblur",
    description: "a modern bloom effect that breathes between crisp and hazy",
    family: "soft_blur_bloom",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "filter_blur",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 0, color: "var(--ink)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 18,
        color: "color-mix(in srgb,var(--ink-2) 45%,transparent)",
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 34,
        color: "color-mix(in srgb,var(--ink-3) 35%,transparent)",
      },
    ],
    blurRadius: 1.6,
  },
  {
    id: 47,
    name: "Laser-Cut",
    slug: "laser",
    description: "a hot scanning blade carves a bright split through the word",
    family: "cutout_layers",
    staticCaps: [
      "gradient_fill",
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [{ offsetX: 0, offsetY: 0, blur: 10, color: "var(--ink-2)" }],
  },
  {
    id: 48,
    name: "Microchip",
    slug: "microchip",
    description: "circuit-board traces scroll beneath monospaced letter masks",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 49,
    name: "Heatmap",
    slug: "heatmap",
    description: "thermal colour blooms migrate across dense letter shapes",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 50,
    name: "Parallax",
    slug: "parallax",
    description: "coloured shadow layers drift at different speeds per letter",
    family: "emboss_3d",
    staticCaps: ["letter_spacing", "ink_tokens", "text_shadow_stack", "multi_text_shadow"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 4, offsetY: 4, blur: 0, color: "color-mix(in srgb,var(--ink-2) 72%,transparent)" },
      {
        offsetX: -4,
        offsetY: -3,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-3) 72%,transparent)",
      },
      { offsetX: 4, offsetY: 4, blur: 0, color: "color-mix(in srgb,var(--ink-2) 72%,transparent)" },
      {
        offsetX: -4,
        offsetY: -3,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-3) 72%,transparent)",
      },
      { offsetX: 8, offsetY: 2, blur: 0, color: "color-mix(in srgb,var(--ink-2) 72%,transparent)" },
      {
        offsetX: -8,
        offsetY: -1,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-3) 72%,transparent)",
      },
    ],
  },
  {
    id: 51,
    name: "Ink-Trap",
    slug: "inktrap",
    description: "editorial serif-like traps pulse as heavy ink floods corners",
    family: "outline_stroke",
    staticCaps: [
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_stroke",
      "mix_blend",
    ],
    letterSpacingEm: 0.04,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    blend: "screen",
    stroke: { width: 1, color: "var(--ink-3)" },
    shadows: [],
  },
  {
    id: 52,
    name: "Topographic",
    slug: "topographic",
    description: "contour-map lines crawl through the text fill",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 53,
    name: "Signal-Noise",
    slug: "signal",
    description: "broadcast interference bends the word into noisy bands",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "filter_blur",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: 3, offsetY: 0, opacity: 0.7 },
      { color: "var(--ink-3)", offsetX: -3, offsetY: 0, opacity: 0.7 },
    ],
  },
  {
    id: 54,
    name: "Portal",
    slug: "portal",
    description: "a conic vortex opens inside the letters and rotates behind them",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "skew_rotate",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 55,
    name: "Tilt-Shift",
    slug: "tiltshift",
    description: "a sharp focal strip travels through blurred duplicate text",
    family: "soft_blur_bloom",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "filter_blur",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink) 28%, transparent)",
    shadows: [],
    blurRadius: 4,
  },
  {
    id: 56,
    name: "Duotone",
    slug: "duotone",
    description: "two offset colour plates slide across a crisp centre layer",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "mix_blend",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    blend: "screen",
    shadows: [],
    offsetFills: [
      { color: "var(--ink-2)", offsetX: -3, offsetY: 0, opacity: 0.85, blendMode: "screen" },
      { color: "var(--ink-3)", offsetX: 3, offsetY: 0, opacity: 0.85, blendMode: "screen" },
    ],
  },
  {
    id: 57,
    name: "Glyph-Rain",
    slug: "glyphrain",
    description: "characters fall in staggered vertical trails and re-form",
    family: "frozen_motion",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      {
        offsetX: 0,
        offsetY: -12,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-3) 45%,transparent)",
      },
      {
        offsetX: 0,
        offsetY: -24,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 28%,transparent)",
      },
    ],
  },
  {
    id: 58,
    name: "Zoetrope",
    slug: "zoetrope",
    description: "letters whirl on a spinning 3D drum, one frame after another",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "filter_blur"],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 59,
    name: "Dot-Matrix",
    slug: "dotmatrix",
    description: "halftone dot letters printed row by row under a bright head",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 60,
    name: "Pendulum",
    slug: "pendulum",
    description: "letters swing from an unseen pivot in staggered phase",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "skew_rotate"],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 61,
    name: "Smoke-Signal",
    slug: "smoke",
    description: "letters curl upward and dissipate like smoke, then re-form",
    family: "soft_blur_bloom",
    staticCaps: ["letter_spacing", "ink_tokens", "opacity_layers", "filter_blur", "skew_rotate"],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
    blurRadius: 3,
  },
  {
    id: 62,
    name: "Eclipse",
    slug: "eclipse",
    description: "a dark moon crosses the glowing word and dims it in passing",
    family: "cutout_layers",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      {
        offsetX: 0,
        offsetY: 0,
        blur: 10,
        color: "color-mix(in srgb,var(--ink-2) 70%,transparent)",
      },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 26,
        color: "color-mix(in srgb,var(--ink-2) 40%,transparent)",
      },
    ],
  },
  {
    id: 63,
    name: "Barcode",
    slug: "barcode",
    description: "striped code bars fill the word while a red beam scans it",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 64,
    name: "Frostbite",
    slug: "frost",
    description: "ice creeps up the letters under a crystalline shimmer",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 65,
    name: "Moiré",
    slug: "moire",
    description: "two line screens drift against each other, weaving interference bands",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 66,
    name: "Rubber-Stamp",
    slug: "stamp",
    description: "the word slams down like an ink stamp, then fades off the page",
    family: "texture_fill",
    staticCaps: ["letter_spacing", "ink_tokens", "opacity_layers", "filter_blur", "skew_rotate"],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink-2)",
    shadows: [],
  },
  {
    id: 67,
    name: "LED-Board",
    slug: "led",
    description: "stadium LED matrix letters with a chasing brightness sweep",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "text_shadow_stack",
      "drop_shadow",
      "mask",
    ],
    letterSpacingEm: 0.18,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: true,
    inkColor: "color-mix(in srgb, var(--ink-2) 22%, transparent)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 1, color: "color-mix(in srgb,var(--ink-2) 35%,transparent)" },
    ],
  },
  {
    id: 68,
    name: "Light-Leak",
    slug: "lightleak",
    description: "cinematic colour veils wash diagonally through the word",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "filter_blur",
      "mix_blend",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    blend: "screen",
    shadows: [],
  },
  {
    id: 69,
    name: "Kilovolt",
    slug: "voltage",
    description: "letters crackle with staggered electric discharge flashes",
    family: "neon_glow",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 4, color: "#fff" },
      { offsetX: 0, offsetY: 0, blur: 14, color: "var(--ink-3)" },
      { offsetX: 2, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: -2, offsetY: 0, blur: 0, color: "var(--ink-3)" },
      { offsetX: 0, offsetY: 0, blur: 10, color: "var(--ink-3)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 22,
        color: "color-mix(in srgb,var(--ink-3) 70%,transparent)",
      },
      { offsetX: 0, offsetY: 0, blur: 6, color: "var(--ink-2)" },
      { offsetX: 0, offsetY: 0, blur: 18, color: "var(--ink-2)" },
      { offsetX: -1, offsetY: 0, blur: 0, color: "var(--ink-3)" },
    ],
  },
  {
    id: 70,
    name: "Carrara",
    slug: "marble",
    description: "liquid marble veins drift through polished stone letterforms",
    family: "chrome_metal",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 71,
    name: "Ripple",
    slug: "ripple",
    description: "concentric water rings expand through the word like a pond splash",
    family: "liquid_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "mix_blend",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink-3) 55%, var(--ink))",
    blend: "screen",
    shadows: [],
  },
  {
    id: 72,
    name: "Shatter",
    slug: "shatter",
    description: "letters fracture outward then snap back into place",
    family: "cutout_layers",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "filter_blur",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 2, offsetY: 0, blur: 0, color: "color-mix(in srgb,var(--ink-3) 70%,transparent)" },
      {
        offsetX: -2,
        offsetY: 0,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 70%,transparent)",
      },
    ],
  },
  {
    id: 73,
    name: "Film-Grain",
    slug: "grain",
    description: "analogue silver-halide noise crawls over the letterforms",
    family: "texture_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "mix_blend",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    blend: "soft-light",
    shadows: [],
  },
  {
    id: 74,
    name: "Caustics",
    slug: "caustic",
    description: "underwater light ribbons swim and refract through the word",
    family: "liquid_fill",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 75,
    name: "Origami",
    slug: "fold",
    description: "paper letters hinge open on staggered folds, then tuck shut",
    family: "frozen_motion",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      {
        offsetX: 4,
        offsetY: 0,
        blur: 10,
        color: "color-mix(in srgb,var(--ink-2) 35%,transparent)",
      },
      {
        offsetX: -3,
        offsetY: 0,
        blur: 8,
        color: "color-mix(in srgb,var(--ink-3) 30%,transparent)",
      },
    ],
  },
  {
    id: 76,
    name: "Domino",
    slug: "domino",
    description: "letters topple in a chain reaction, then spring back upright",
    family: "frozen_motion",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "text_shadow_stack",
      "skew_rotate",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 1, offsetY: 0, blur: 0, color: "color-mix(in srgb,var(--ink-3) 25%,transparent)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 14,
        color: "color-mix(in srgb,var(--ink-2) 60%,transparent)",
      },
      { offsetX: 0, offsetY: 0, blur: 6, color: "color-mix(in srgb,var(--ink-2) 30%,transparent)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 10,
        color: "color-mix(in srgb,var(--ink-3) 45%,transparent)",
      },
      { offsetX: 1, offsetY: 0, blur: 0, color: "color-mix(in srgb,var(--ink-3) 25%,transparent)" },
    ],
  },
  {
    id: 77,
    name: "Zip-Merge",
    slug: "zipper",
    description: "letters interlock like zipper teeth behind a travelling slider",
    family: "frozen_motion",
    staticCaps: [
      "gradient_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "opacity_layers",
      "skew_rotate",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 78,
    name: "Equalizer",
    slug: "equalizer",
    description: "letters ride the peaks of a pumping audio meter",
    family: "frozen_motion",
    staticCaps: ["gradient_fill", "ink_tokens", "pseudo_layers", "text_shadow_stack"],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [{ offsetX: 0, offsetY: 0, blur: 16, color: "var(--ink-2)" }],
  },
  {
    id: 79,
    name: "Mercury",
    slug: "gooey",
    description: "liquid-metal letters puddle together, then reform",
    family: "chrome_metal",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 80,
    name: "Sonar",
    slug: "sonar",
    description: "a radar sweep lights the word like a returning ping",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "drop_shadow",
    ],
    letterSpacingEm: 0.16,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink-3) 40%, var(--ink))",
    shadows: [],
  },
  {
    id: 81,
    name: "Hyperspace",
    slug: "warp",
    description: "letters punch out of deep Z and blow past the camera",
    family: "frozen_motion",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "opacity_layers",
      "text_shadow_stack",
      "filter_blur",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: 0, offsetY: 0, blur: 12, color: "var(--ink-3)" },
      {
        offsetX: 0,
        offsetY: 0,
        blur: 28,
        color: "color-mix(in srgb,var(--ink-2) 70%,transparent)",
      },
      { offsetX: 0, offsetY: 0, blur: 22, color: "var(--ink-2)" },
    ],
  },
  {
    id: 82,
    name: "Ghostwrite",
    slug: "shimmer",
    description: "the AI shimmer: a soft luminance band sweeps muted letters",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
    ],
    letterSpacingEm: 0.14,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 83,
    name: "Tickertape",
    slug: "ticker",
    description:
      "endless editorial marquee gliding one seamless loop (the word repeats five times; the track slides exactly one copy width)",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 84,
    name: "Kaboom",
    slug: "kaboom",
    description: "the word crashes in from nowhere with an RGB shake and shockwave",
    family: "glitch_offset",
    staticCaps: [
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "opacity_layers",
      "text_shadow_stack",
      "filter_blur",
      "multi_text_shadow",
      "data_text_dupe",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [
      { offsetX: -6, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: 6, offsetY: 0, blur: 0, color: "var(--ink-3)" },
      { offsetX: -2, offsetY: 0, blur: 0, color: "var(--ink-2)" },
      { offsetX: 2, offsetY: 0, blur: 0, color: "var(--ink-3)" },
    ],
    offsetFills: [
      { color: "#ff3355", offsetX: -4, offsetY: 2, opacity: 0.75 },
      { color: "#33ddff", offsetX: 4, offsetY: -2, opacity: 0.75 },
    ],
  },
  {
    id: 85,
    name: "Lyric-Fill",
    slug: "karaoke",
    description: "karaoke highlight paints each letter left-to-right with a bounce",
    family: "gradient_aurora",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "drop_shadow",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "color-mix(in srgb, var(--ink) 42%, transparent)",
    shadows: [],
  },
  {
    id: 86,
    name: "Lenti-Card",
    slug: "lenticular",
    description: "a holographic trading card tilts, ridge-stripes flipping colour",
    family: "holographic",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "data_text_dupe",
      "opacity_layers",
      "skew_rotate",
      "mask",
    ],
    letterSpacingEm: 0.12,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: true,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 87,
    name: "Helium",
    slug: "balloon",
    description: "balloon letters inflate from flat, catch a highlight, then deflate",
    family: "frozen_motion",
    staticCaps: [
      "gradient_fill",
      "bg_clip_text",
      "transparent_fill",
      "letter_spacing",
      "ink_tokens",
      "filter_blur",
      "skew_rotate",
      "drop_shadow",
    ],
    letterSpacingEm: 0.06,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 88,
    name: "Liquid-Lens",
    slug: "lens",
    description:
      "a glass puck glides over the word: a soft-masked copy refracts the letters while the puck itself is clipped to an ellipse (clip-path, not a mask — a mask does not clip `backdrop-filter`)",
    family: "soft_blur_bloom",
    staticCaps: [
      "gradient_fill",
      "letter_spacing",
      "ink_tokens",
      "clip_path",
      "pseudo_layers",
      "data_text_dupe",
      "text_shadow_stack",
      "filter_blur",
      "mask",
      "multi_text_shadow",
    ],
    letterSpacingEm: 0.1,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: true,
    hasBoxReflect: false,
    hasMask: true,
    inkColor: "color-mix(in srgb, var(--ink) 78%, transparent)",
    shadows: [
      {
        offsetX: -2,
        offsetY: 0,
        blur: 0,
        color: "color-mix(in srgb,var(--ink-2) 70%,transparent)",
      },
      { offsetX: 2, offsetY: 0, blur: 0, color: "color-mix(in srgb,var(--ink-3) 70%,transparent)" },
    ],
    blurRadius: 1.5,
  },
  {
    id: 89,
    name: "Whiplash",
    slug: "smear",
    description:
      "letters whip in on a stretched motion-blur smear, land with a squash, then get dragged off the other side",
    family: "frozen_motion",
    staticCaps: ["letter_spacing", "ink_tokens", "opacity_layers", "filter_blur", "skew_rotate"],
    letterSpacingEm: 0.08,
    sourceHasAnimation: true,
    hasPseudo: false,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
  {
    id: 90,
    name: "Keycap",
    slug: "keycap",
    description:
      "mechanical keycaps bottom out one after another, the skirt collapsing under each cap as it clicks",
    family: "emboss_3d",
    staticCaps: [
      "gradient_fill",
      "letter_spacing",
      "ink_tokens",
      "pseudo_layers",
      "opacity_layers",
      "filter_blur",
      "skew_rotate",
    ],
    letterSpacingEm: 0.02,
    sourceHasAnimation: true,
    hasPseudo: true,
    hasClipPath: false,
    hasBoxReflect: false,
    hasMask: false,
    inkColor: "var(--ink)",
    shadows: [],
  },
];
