/**
 * Static map of Prompt Helper option IDs → VPS-served thumbnail URLs.
 * Regenerated by `scripts/generate-prompt-helper-thumbs.mjs`.
 */
export const PROMPT_HELPER_THUMB_SRCS: Readonly<Record<string, string>> = {
  "3d": "/prompt-helper/thumbs/3d.jpg",
  "abstract": "/prompt-helper/thumbs/abstract.jpg",
  "cinematic": "/prompt-helper/thumbs/cinematic.jpg",
  "closeup": "/prompt-helper/thumbs/closeup.jpg",
  "dark": "/prompt-helper/thumbs/dark.jpg",
  "density_airy": "/prompt-helper/thumbs/density_airy.jpg",
  "density_centered": "/prompt-helper/thumbs/density_centered.jpg",
  "density_dense": "/prompt-helper/thumbs/density_dense.jpg",
  "density_left": "/prompt-helper/thumbs/density_left.jpg",
  "earth": "/prompt-helper/thumbs/earth.jpg",
  "flat": "/prompt-helper/thumbs/flat.jpg",
  "front": "/prompt-helper/thumbs/front.jpg",
  "isometric": "/prompt-helper/thumbs/isometric.jpg",
  "mood_drama": "/prompt-helper/thumbs/mood_drama.jpg",
  "mood_energy": "/prompt-helper/thumbs/mood_energy.jpg",
  "mood_graphic": "/prompt-helper/thumbs/mood_graphic.jpg",
  "mood_minimal": "/prompt-helper/thumbs/mood_minimal.jpg",
  "mood_premium": "/prompt-helper/thumbs/mood_premium.jpg",
  "nature": "/prompt-helper/thumbs/nature.jpg",
  "neon": "/prompt-helper/thumbs/neon.jpg",
  "painting": "/prompt-helper/thumbs/painting.jpg",
  "pastel": "/prompt-helper/thumbs/pastel.jpg",
  "photorealistic": "/prompt-helper/thumbs/photorealistic.jpg",
  "room": "/prompt-helper/thumbs/room.jpg",
  "sig_bold": "/prompt-helper/thumbs/sig_bold.jpg",
  "sig_corner": "/prompt-helper/thumbs/sig_corner.jpg",
  "sig_frame": "/prompt-helper/thumbs/sig_frame.jpg",
  "sig_stroke": "/prompt-helper/thumbs/sig_stroke.jpg",
  "struct_flat": "/prompt-helper/thumbs/struct_flat.jpg",
  "struct_frame": "/prompt-helper/thumbs/struct_frame.jpg",
  "struct_gradient": "/prompt-helper/thumbs/struct_gradient.jpg",
  "struct_split": "/prompt-helper/thumbs/struct_split.jpg",
  "studio": "/prompt-helper/thumbs/studio.jpg",
  "vibrant": "/prompt-helper/thumbs/vibrant.jpg",
};

export function promptHelperThumbSrc(optionId: string): string | undefined {
  return PROMPT_HELPER_THUMB_SRCS[optionId];
}
