import { create } from "zustand";
import type { VisualTaskClass as TaskClass } from "@/lib/ai/visualOrchestrator";
import type { CreativeDirection } from "./creativeDirector";

/**
 * Unique identifier for a session snapshot or turn.
 */
export type SessionId = string;

/**
 * Lightweight summary of an Object in the Artwork for AI context.
 * Excludes heavy binary/base64 payloads to keep memory < 5KB per turn.
 */
export type ArtworkObjectSummary = {
  id: string;
  type: string;
  layerId: string;
  x: number;
  y: number;
  width: number;
  height: number;
  label?: string;
  textSnippet?: string;
  assetHash?: string;
  isLocked?: boolean;
};

/**
 * Canonical Artifact snapshot captured at a stable point in the conversation.
 * Tied to the Undo/Redo timeline in `lib/engine/store.ts`.
 */
export type CanonicalArtifactSnapshot = {
  id: string;
  timestamp: number;
  historyIndex: number;
  width: number;
  height: number;
  objects: readonly ArtworkObjectSummary[];
  activeSelectionIds: readonly string[];
};

/**
 * Candidate Variation generated by batch runner (1-5 outputs).
 */
export type CandidateVariation = {
  id: string;
  url: string;
  brief: string;
  dimensions: { width: number; height: number };
  status: "staged" | "ghost_preview" | "accepted" | "rejected";
  suggestedPlacement?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
};

/**
 * Record of a single turn in the multi-turn session.
 */
export type DirectorSessionTurn = {
  id: string;
  timestamp: number;
  role: "user" | "assistant";
  content: string;
  taskClass?: TaskClass;
  direction?: CreativeDirection;
  associatedSnapshotId?: string;
  stagedVariations?: readonly CandidateVariation[];
  acceptedVariationId?: string;
};

/**
 * Client-owned Stateful Session for Creative Director.
 * Managed via Zustand in the browser; strictly stateless on server API.
 */
export type CreativeDirectorSessionState = {
  sessionId: string;
  activeSlideId: string;
  turns: readonly DirectorSessionTurn[];
  snapshots: Record<string, CanonicalArtifactSnapshot>;
  currentSnapshotId?: string;
  activeGhostVariationId?: string;

  // Actions
  appendUserTurn: (prompt: string, taskClass?: TaskClass) => DirectorSessionTurn;
  appendAssistantTurn: (
    direction: CreativeDirection,
    content: string,
    variations?: readonly CandidateVariation[],
  ) => DirectorSessionTurn;
  captureSnapshot: (
    slideId: string,
    historyIndex: number,
    width: number,
    height: number,
    objects: readonly ArtworkObjectSummary[],
    selectedIds: readonly string[],
  ) => CanonicalArtifactSnapshot;
  setGhostPreview: (variationId: string | undefined) => void;
  acceptVariation: (turnId: string, variationId: string) => void;
  rejectVariation: (turnId: string, variationId: string) => void;
  clearSession: () => void;

  // Context export for stateless API request
  buildDirectorTurnContext: (maxTurns?: number) => {
    conversationHistory: { role: "user" | "assistant"; content: string }[];
    canonicalSummary: {
      width: number;
      height: number;
      objectCount: number;
      selectedCount: number;
      objects: readonly ArtworkObjectSummary[];
    };
  };
};

/**
 * Pure function to summarize objects for lightweight context transfer.
 */
export function summarizeArtworkObjects(
  elements: readonly Record<string, unknown>[],
): ArtworkObjectSummary[] {
  return elements.map((el) => ({
    id: String(el.id),
    type: String(el.type ?? "object"),
    layerId: String(el.layerId ?? "default"),
    x: Math.round(Number(el.x ?? 0)),
    y: Math.round(Number(el.y ?? 0)),
    width: Math.round(Number(el.width ?? 0)),
    height: Math.round(Number(el.height ?? 0)),
    label: el.label ? String(el.label) : undefined,
    textSnippet: el.text ? String(el.text).slice(0, 80) : undefined,
    isLocked: Boolean(el.locked),
  }));
}

/**
 * Creates initial state for CreativeDirectorSession.
 */
export function createInitialSessionState(
  activeSlideId: string,
  sessionId = `session_${Date.now()}`,
): Pick<
  CreativeDirectorSessionState,
  | "sessionId"
  | "activeSlideId"
  | "turns"
  | "snapshots"
  | "currentSnapshotId"
  | "activeGhostVariationId"
> {
  return {
    sessionId,
    activeSlideId,
    turns: [],
    snapshots: {},
    currentSnapshotId: undefined,
    activeGhostVariationId: undefined,
  };
}

/**
 * Zustand client store for managing the Creative Director Session.
 * Strictly client-owned; provides local-first context to stateless server APIs.
 */
export const useDirectorSession = create<CreativeDirectorSessionState>((set, get) => ({
  ...createInitialSessionState("default-slide"),

  appendUserTurn: (prompt: string, taskClass?: TaskClass) => {
    const turn: DirectorSessionTurn = {
      id: `turn_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      timestamp: Date.now(),
      role: "user",
      content: prompt,
      taskClass,
    };
    set((state) => ({
      turns: [...state.turns, turn],
    }));
    return turn;
  },

  appendAssistantTurn: (
    direction: CreativeDirection,
    content: string,
    variations?: readonly CandidateVariation[],
  ) => {
    const turn: DirectorSessionTurn = {
      id: `turn_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      timestamp: Date.now(),
      role: "assistant",
      content,
      direction,
      stagedVariations: variations ? [...variations] : undefined,
    };
    set((state) => ({
      turns: [...state.turns, turn],
    }));
    return turn;
  },

  captureSnapshot: (
    slideId: string,
    historyIndex: number,
    width: number,
    height: number,
    objects: readonly ArtworkObjectSummary[],
    selectedIds: readonly string[],
  ) => {
    const snapshot: CanonicalArtifactSnapshot = {
      id: `snap_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      timestamp: Date.now(),
      historyIndex,
      width,
      height,
      objects,
      activeSelectionIds: selectedIds,
    };
    set((state) => ({
      activeSlideId: slideId,
      currentSnapshotId: snapshot.id,
      snapshots: {
        ...state.snapshots,
        [snapshot.id]: snapshot,
      },
    }));
    return snapshot;
  },

  setGhostPreview: (variationId: string | undefined) => {
    set({ activeGhostVariationId: variationId });
  },

  acceptVariation: (turnId: string, variationId: string) => {
    set((state) => {
      const turns = state.turns.map((t) => {
        if (t.id !== turnId) return t;
        const updatedVariations = t.stagedVariations?.map((v) => ({
          ...v,
          status: v.id === variationId ? ("accepted" as const) : ("rejected" as const),
        }));
        return {
          ...t,
          acceptedVariationId: variationId,
          stagedVariations: updatedVariations,
        };
      });
      return { turns, activeGhostVariationId: undefined };
    });
  },

  rejectVariation: (turnId: string, variationId: string) => {
    set((state) => {
      const turns = state.turns.map((t) => {
        if (t.id !== turnId) return t;
        const updatedVariations = t.stagedVariations?.map((v) =>
          v.id === variationId ? { ...v, status: "rejected" as const } : v,
        );
        return {
          ...t,
          stagedVariations: updatedVariations,
        };
      });
      return {
        turns,
        activeGhostVariationId:
          state.activeGhostVariationId === variationId ? undefined : state.activeGhostVariationId,
      };
    });
  },

  clearSession: () => {
    set({
      turns: [],
      snapshots: {},
      currentSnapshotId: undefined,
      activeGhostVariationId: undefined,
    });
  },

  buildDirectorTurnContext: (maxTurns = 12) => {
    const state = get();
    const history = state.turns.slice(-maxTurns).map((t) => ({
      role: t.role,
      content: t.content,
    }));
    const currentSnap = state.currentSnapshotId
      ? state.snapshots[state.currentSnapshotId]
      : undefined;
    return {
      conversationHistory: history,
      canonicalSummary: {
        width: currentSnap?.width ?? 1920,
        height: currentSnap?.height ?? 1080,
        objectCount: currentSnap?.objects.length ?? 0,
        selectedCount: currentSnap?.activeSelectionIds.length ?? 0,
        objects: currentSnap?.objects ?? [],
      },
    };
  },
}));
