import type { VisualTaskClass as TaskClass } from "@/lib/ai/visualOrchestrator";
import type { CreativeDirection } from "./creativeDirector";

/**
 * Unique identifier for a session snapshot or turn.
 */
export type SessionId = string;

/**
 * Lightweight summary of an Object in the Artwork for AI context.
 * Excludes heavy binary/base64 payloads to keep memory < 5KB per turn.
 */
export type ArtworkObjectSummary = {
  id: string;
  type: string;
  layerId: string;
  x: number;
  y: number;
  width: number;
  height: number;
  label?: string;
  textSnippet?: string;
  assetHash?: string;
  isLocked?: boolean;
};

/**
 * Canonical Artifact snapshot captured at a stable point in the conversation.
 * Tied to the Undo/Redo timeline in `lib/engine/store.ts`.
 */
export type CanonicalArtifactSnapshot = {
  id: string;
  timestamp: number;
  historyIndex: number;
  width: number;
  height: number;
  objects: readonly ArtworkObjectSummary[];
  activeSelectionIds: readonly string[];
};

/**
 * Candidate Variation generated by batch runner (1-5 outputs).
 */
export type CandidateVariation = {
  id: string;
  url: string;
  brief: string;
  dimensions: { width: number; height: number };
  status: "staged" | "ghost_preview" | "accepted" | "rejected";
  suggestedPlacement?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
};

/**
 * Record of a single turn in the multi-turn session.
 */
export type DirectorSessionTurn = {
  id: string;
  timestamp: number;
  role: "user" | "assistant";
  content: string;
  taskClass?: TaskClass;
  direction?: CreativeDirection;
  associatedSnapshotId?: string;
  stagedVariations?: readonly CandidateVariation[];
  acceptedVariationId?: string;
};

/**
 * Client-owned Stateful Session for Creative Director.
 * Managed via Zustand in the browser; strictly stateless on server API.
 */
export type CreativeDirectorSessionState = {
  sessionId: string;
  activeSlideId: string;
  turns: readonly DirectorSessionTurn[];
  snapshots: Record<string, CanonicalArtifactSnapshot>;
  currentSnapshotId?: string;
  activeGhostVariationId?: string;

  // Actions
  appendUserTurn: (prompt: string, taskClass?: TaskClass) => DirectorSessionTurn;
  appendAssistantTurn: (
    direction: CreativeDirection,
    content: string,
    variations?: readonly CandidateVariation[],
  ) => DirectorSessionTurn;
  captureSnapshot: (
    slideId: string,
    historyIndex: number,
    width: number,
    height: number,
    objects: readonly ArtworkObjectSummary[],
    selectedIds: readonly string[],
  ) => CanonicalArtifactSnapshot;
  setGhostPreview: (variationId: string | undefined) => void;
  acceptVariation: (turnId: string, variationId: string) => void;
  rejectVariation: (turnId: string, variationId: string) => void;
  clearSession: () => void;

  // Context export for stateless API request
  buildDirectorTurnContext: (maxTurns?: number) => {
    conversationHistory: { role: "user" | "assistant"; content: string }[];
    canonicalSummary: {
      width: number;
      height: number;
      objectCount: number;
      selectedCount: number;
      objects: readonly ArtworkObjectSummary[];
    };
  };
};

/**
 * Pure function to summarize objects for lightweight context transfer.
 */
export function summarizeArtworkObjects(
  elements: readonly Record<string, unknown>[],
): ArtworkObjectSummary[] {
  return elements.map((el) => ({
    id: String(el.id),
    type: String(el.type ?? "object"),
    layerId: String(el.layerId ?? "default"),
    x: Math.round(Number(el.x ?? 0)),
    y: Math.round(Number(el.y ?? 0)),
    width: Math.round(Number(el.width ?? 0)),
    height: Math.round(Number(el.height ?? 0)),
    label: el.label ? String(el.label) : undefined,
    textSnippet: el.text ? String(el.text).slice(0, 80) : undefined,
    isLocked: Boolean(el.locked),
  }));
}

/**
 * Creates initial state for CreativeDirectorSession.
 */
export function createInitialSessionState(
  activeSlideId: string,
  sessionId = `session_${Date.now()}`,
): Pick<
  CreativeDirectorSessionState,
  | "sessionId"
  | "activeSlideId"
  | "turns"
  | "snapshots"
  | "currentSnapshotId"
  | "activeGhostVariationId"
> {
  return {
    sessionId,
    activeSlideId,
    turns: [],
    snapshots: {},
    currentSnapshotId: undefined,
    activeGhostVariationId: undefined,
  };
}
